### PR TITLE
Fix using features

### PR DESCRIPTION
**Pull request by EPashkin**
@gkoz  ?

### CODE REVIEW

**Comment by EPashkin** [comment]
Not tested that script part still works.

**Comment by EPashkin** [comment]
Error before this PR `version components must be numeric` so old variant just tried load crate `features` from `crates.io` and not worked anyway.

**Comment by gkoz** [comment]
Thanks for noticing this! Unfortunately there seems to be an issue with highlighting this kind of toml syntax (the highlighter thinks it's broken, at least on my machine), so we need to either choose the more usual one
```toml
[dependencies.gtk]
version = "..."
features = ["..."]
```
or remove the "toml" hint.

**Comment by EPashkin** [comment]
It come from gitter

**Comment by EPashkin** [comment]
Updated

**Comment by gkoz** [comment]
Thanks!

**Pull request merged**
