### PR TITLE
Example code improvement

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
cc @gkoz

### CODE REVIEW

**Comment by gkoz** [comment]
I'm not enthusiastic about endorsing `.ok().expect(...)`...

**Comment by GuillaumeGomez** [comment]
Hum... Any particular reason ?

**Comment by gkoz** [comment]
It works here because our error type is `()` but generally is inferior to `Result::expect` and seems the opposite of idiomatic. People will use pieces of our examples without questioning them. Maybe we should replace the panic with `print!` and `return`.

**Comment by GuillaumeGomez** [comment]
I'd prefer this actually. I'm not a big fan of `panic!` when it's not absolutely necessary.

**Comment by gkoz** [comment]
We should start by updating the actual example(s) anyway and then bring the change here.

**Comment by GuillaumeGomez** [comment]
Actually, it doesn't seem to be a priority but if you have nothing else waiting, then I let you update examples. ;)

**Comment by gkoz** [comment]
I'm working on push some hand-generated docs after that maybe.

**Comment by GuillaumeGomez** [comment]
As you wish, I'm starting to prepare to push on crates.io tomorrow.

**Comment by gkoz** [comment]
I've found a little issue with the version handling and enums in cairo. Might want to hold off pusblishing crates a bit.

**Comment by GuillaumeGomez** [comment]
Ok, I'm in standby. Just email me when the situation is unlocked please. ^^

**Comment by gkoz** [comment]
I've just learnt more about the issue. Good news is, it's not a crates showstopper.

Turns out rustdoc doesn't get the same `cfg` directives `rustc` gets so it can't see any of the gated stuff. WAT

**Comment by GuillaumeGomez** [comment]
DARK MAGIC !!!
Well, I work on crates tomorrow now. Witches will wait !

**Comment by gkoz** [comment]
Looks like we've resolved this in a different way.

**Pull request closed without merging**
