### PR TITLE
 Add blog navigation and redesign article overview

### PR DESCRIPTION
**Pull request by sophie-h**
I still have this lying around.

Screenshot-20210619170954-1072x1090
Screenshot-20210619170917-1072x1090

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Could we make the text less wide? Keeping it under 80 characters per line help the reading iirc.

**Comment by sophie-h** [comment]
> Could we make the text less wide?

Oh yes, please! Also for the start page? We would have to tune things a bit to make it fit.

Maybe also switch to Roboto instead of some random sans-serif font?

# Current

image

# Roboto

image

# Cantarell

image

# Robot (weight 300)

image

**Comment by sophie-h** [comment]
Start page with 620px

image

**Comment by sdroege** [comment]
> Start page with 620px

Looks good to me :)

**Comment by GuillaumeGomez** [comment]
> Oh yes, please! Also for the start page?

Yes please! :)

> Text is a bit small in your last screenshot.

Also, sounds good for roboto!

**Comment by sophie-h** [comment]
Using slick font again for arrows. Ready for review.

image

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
