### PR TITLE
Create 2016-11-27-more-versions.md

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
cc @EPashkin

### CODE REVIEW

**Comment by EPashkin** [comment]
Now year 2016

**Comment by GuillaumeGomez** [comment]
Urg!

**Comment by EPashkin** [comment]
Not sure how to say it, but IMHO better add that changes don't include new functions from upgrades.

**Comment by EPashkin** [comment]
File still 2015

**Comment by GuillaumeGomez** [comment]
Not when you said "File still 2015". :p

**Comment by EPashkin** [comment]
Thanks

**Comment by EPashkin** [comment]
Hm, seems better update version on main page too.
In
```
[dependencies.gtk]
version = "0.1.0"
features = ["v3_10"]
```

**Comment by GuillaumeGomez** [comment]
> Not sure how to say it, but IMHO better add that changes don't include new functions from upgrades.

I think it's better to avoid giving too much details.

> Hm, seems better update version on main page too.

Could you do it please? :)

**Comment by GuillaumeGomez** [comment]
I have to leave so I'll merge as is. Don't hesitate to open a PR if you want to improve anything, I'll try to merge it tomorrow morning.

**Pull request merged**
