### PR TITLE
Simplify index page and design

### PR DESCRIPTION
**Pull request by sophie-h**
- Design fix for footer on mobile
- Simplify index.md
- Move projects to json for future changes
- Other small design fixes
- Deliver Cantarell font

### CODE REVIEW

**Comment by sophie-h** [comment]
@GuillaumeGomez can you review this?

**Comment by GuillaumeGomez** [comment]
Need screnshots. :)

**Comment by sophie-h** [comment]
> Need screnshots. :)

Ideally there is not difference here :)

image

**Comment by GuillaumeGomez** [comment]
Oh I expecting some (with the font change at least). Taking a deeper look in the diff then!

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by sophie-h** [comment]
> Oh I expecting some (with the font change at least).

Only for device that don't have Cantarell installed.

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
