### PR TITLE
Use shileds for crates version

### LINKED ISSUE #260: fix crate version on homepage
On the homepage the crate version of gtk4 is 0.2.0, but on crates.io it's 0.3.1.

Is there a way to keep it updated automatically? Maybe adding some crates.io badge like 
crates.io

It's just an image to ```https://img.shields.io/crates/v/gtk4.svg```

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
Fixes #260

I didn't test the changes.

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
cc @sophie-h

**Comment by sophie-h** [comment]
Wait, I thought I had left a comment here. Where did that go? xD

**Comment by sophie-h** [comment]
Whatever, my comment was that I thought that the orange might not be the best fit and here are some ideas

Screenshot from 2023-02-19 01-05-30

Also, we should make the badge link to the crate I guess

**Comment by sdroege** [comment]
> Wait, I thought I had left a comment here. Where did that go? xD

[Here](https://github.com/gtk-rs/gtk-rs.github.io/issues/260#issuecomment-1435796779) :)

**Comment by bilelmoussaoui** [comment]
Pushed the changes to the main branch directly.

**Pull request closed without merging**
