### PR TITLE
Update requirements on Windows

### PR DESCRIPTION
**Pull request by gkoz**
[Rendered](https://github.com/gkoz/gtk-rs.github.io/blob/sdk-windows/docs-src/requirements.md).
Let's see if anyone can test/confirm this first...

### CODE REVIEW

**Comment by gkoz** [comment]
cc @rnestler

**Comment by GuillaumeGomez** [comment]
He said on gitter that it worked.

**Comment by rnestler** [comment]
I can look at it tomorrow evening. Looks simpler now :smiley:

**Comment by rnestler** [comment]
Hmm I tried it, but I couldn't get it to work yet. At least not with "Using the native Windows shell". I installed msys2 and rust 1.7 on a clean Windows7 VM. I will try it using the Mingw32 shell tonight. Maybe I just set PATH wrong or something.

**Comment by gkoz** [comment]
Thanks @rnestler!
Let's merge then.

**Comment by GuillaumeGomez** [comment]
Thanks @gkoz!

**Pull request merged**
