### PR TITLE
Add post for new release

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
cc @EPashkin

### CODE REVIEW

**Comment by EPashkin** [comment]
Update version in `_data/crates.json` (changes badges and first page using example)
Important: Added not only child properties but "almost all" normal properties too.

**Comment by GuillaumeGomez** [comment]
Better? :)

**Comment by EPashkin** [comment]
"all" properties not right, but may be it normal :wink:

**Comment by GuillaumeGomez** [comment]
Oh you're right. I removed "all". Anything else?

**Comment by EPashkin** [comment]
All seems ok

**Comment by GuillaumeGomez** [comment]
Thanks for your review!

**Pull request merged**
