### PR TITLE
Add blog post about logos and logos

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
cc @sdroege @EPashkin

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Once validated, I'll also change the organization's logo.

**Comment by sdroege** [comment]
Need to check the trademark situation of both Rust and GNOME logo, otherwise seems fine to me

**Comment by EPashkin** [comment]
👍

**Comment by GuillaumeGomez** [comment]
Rust logo usage seems fine based on their trademarks. I sent a mail to GNOME.

**Comment by sdroege** [comment]
@GuillaumeGomez I guess this can be closed?

**Comment by GuillaumeGomez** [comment]
Yep...

**Pull request closed without merging**
