### PR TITLE
Rename docs-src to docs and move docs repo

### PR DESCRIPTION
**Pull request by jsparber**
This requires the `gtk-rs/docs` repo to be removed or else the folder `docs` is shadowed by the repo.

This is related to https://github.com/gtk-rs/gtk-rs/pull/325, which generates via gh-actions new docs for each stable release and unstable docs for each change to `gtk-rs:master`.

Fixes: #105

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Wait hold on! This repository isn't supposed to host any rustdoc generated documentation.

**Comment by jsparber** [comment]
> Wait hold on! This repository isn't supposed to host any rustdoc generated documentation.

Why not? Why is there a need of the separate `docs` repo?

**Comment by GuillaumeGomez** [comment]
For a simple reason: the docs are super huge. It's far simpler to have a repository to handle them.

**Comment by jsparber** [comment]
> For a simple reason: the docs are super huge. It's far simpler to have a repository to handle them.

I agree that they are huge, but the separate repo makes things more complicated then they need to be.

**Comment by GuillaumeGomez** [comment]
Sorry but I won't accept this change. I want to keep this repository "simple" and having thousands of files is definitely going to help in that regard... Closing then.

**Pull request closed without merging**
