### PR TITLE
Add tutorial page explaining how to crosscompile on Linux to differen…

### PR DESCRIPTION
**Pull request by Cogitri**
…t arches

Note I can't seem to get Jekyll to run, so I can't test this on a live page :/

### CODE REVIEW

**Comment by sdroege** [comment]
Looks good to me, thanks! @GuillaumeGomez ? :)

**Comment by GuillaumeGomez** [comment]
Woups, didn't see this one. Thanks!

**Comment by Cogitri** [comment]
Thanks for merging :)

**Comment by GuillaumeGomez** [comment]
Well, thanks for doing. :laughing:

**Pull request merged**
