### PR TITLE
New release

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
The final piece of the release. Does it seem good to you @EPashkin?

### CODE REVIEW

**Comment by EPashkin** [comment]
Thanks, @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
Sorry, didn't wait for your answer. If you see anything invalid/wrong, don't hesitate to update it!

**Comment by EPashkin** [comment]
No, all good, only IMHO a little prematurely
as we still have https://github.com/gtk-rs/lgpl-docs/pull/30, no `embed-lgpl-docs` in glib.

**Comment by GuillaumeGomez** [comment]
Well, we don't have to wait four months for the next release this time. ;)

**Pull request merged**
